services:
  database:
    container_name: mysql_database_pos_application
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: pos-application
      MYSQL_USER: egin
      MYSQL_PASSWORD: test
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0.11
    restart: always
    ports:
      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data



volumes:
  cache:
    driver: local